name: dreams_come_true_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-246.0.dev <4.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_masonry_view: ^0.0.2
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  localstorage: ^4.0.1+4
  logger: ^2.0.2+1
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/config/.env
    - assets/images/
